/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#000830",
        secondary: "#C59D5C",
        surface: "#F9FAFB",
        "surface-1": "#F6F7F8",
        "surface-2": "#F3F4F6",
        "on-surface-variant": "#4B5563",
        outline: "#E5E7EB",
        paper: "#F3EBD8",
        ink: "#1A1712",
        ledger: "#2F4A3C",
        "navy-deep": "#0A0E1A",
        "navy-mid": "#101628",
        "navy-card": "#161D32",
        "navy-row": "#1C243C",
        "navy-line": "#2C3550",
        mist: "#C5CBD8",
        deny: "#8B3A3A",
        void: "#0B0B0C",
        "void-mid": "#141416",
        "void-card": "#1C1C1F",
        "void-line": "#2E2E33",
        ivory: "#F6F3EC",
        "ivory-2": "#EBE6DA",
        "ivory-ink": "#161513",
        ember: "#2A2118",
        ctrl: "#4F46E5",
        "ctrl-deep": "#3730A3",
        flare: "#E11D48",
        dusk: "#6D28D9",
        amberfield: "#EA580C",
        "mg-ivory": "#F0F0E8",
        "mg-ink": "#141414",
        "mg-indigo": "#5060E0",
        "mg-magenta": "#E040A0",
        "mg-blue": "#5090F0",
        "mg-warm": "#E08070",
        "mg-vinho": "#40101E",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        display: ["Geist", "Inter", "system-ui", "sans-serif"],
        ui: ["Geist", "Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
